-- create table email
-- (
--    PID INTEGER,
--    Pemail varchar(50),
--    CONSTRAINT foreign_key foreign key (PID) references person (PID) ON delete cascade,
--    CONSTRAINT UN UNIQUE (Pemail,PID)
-- );

-- insert into email(PID,Pemail) values (1,'dcz'),
-- (2,'dcz'),
-- (3,'dcz');